/* eslint-disable @typescript-eslint/no-empty-interface */
// This file is automatically generated.
// Please do not change this file!
// eslint-disable-next-line @typescript-eslint/interface-name-prefix
interface CssExports {

}
declare var cssExports: CssExports
export = cssExports;
